"""Generate YAML-to-installed-STIG traceability documentation."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from stig_audit_pro.core.yaml_loader import load_check_library
from stig_audit_pro.stig.stig_metadata import StigBenchmarkMetadata


OUTPUT = ROOT / "docs" / "assurance" / "STIG_TRACEABILITY.md"


def _installed_rules() -> dict[tuple[str, str], tuple[StigBenchmarkMetadata, object]]:
    rules: dict[tuple[str, str], tuple[StigBenchmarkMetadata, object]] = {}
    for path in sorted((ROOT / "data" / "stigs" / "cache").glob("*/metadata.json")):
        try:
            benchmark = StigBenchmarkMetadata.model_validate(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            continue
        for rule in benchmark.rules:
            rules[(benchmark.family, rule.vuln_id)] = (benchmark, rule)
    return rules


def render() -> str:
    installed = _installed_rules()
    rows: list[str] = []
    for path in sorted((ROOT / "data" / "checks").glob("*.yaml")):
        library = load_check_library(path)
        for check in library.checks:
            matched = installed.get((check.stig_family, check.vuln_id))
            benchmark = matched[0] if matched else None
            rule = matched[1] if matched else None
            version = check.source_version or (benchmark.version if benchmark else "") or "—"
            release = check.source_release or (benchmark.release_info if benchmark else "") or "—"
            rule_id = check.rule_id or (getattr(rule, "rule_id", "") if rule else "") or "—"
            automated = "Automated" if check.automated and check.check_type != "manual_review" else "Manual"
            commands = "<br>".join(f"`{command}`" for command in check.commands) or "—"
            review = check.review_status or (
                "Reviewed fingerprint recorded" if check.last_reviewed_stig_fingerprint else "Not recorded"
            )
            rows.append(
                f"| {check.stig_family} | {check.vuln_id} | {rule_id} | {version} / {release} | "
                f"`data/checks/{path.name}` | `{check.check_type}` | {automated} | {commands} | {review} |"
            )
    return "\n".join([
        "# STIG Traceability",
        "",
        "> Generated by `scripts/generate_stig_traceability.py`. Do not edit by hand.",
        "",
        "This table maps the installed STIG metadata and bundled YAML automation. Historical audit runs retain their own snapshots and fingerprints.",
        "",
        "| Family | Vuln ID | Rule ID | STIG version / release | YAML file | Check type | Mode | Commands | Review status |",
        "|---|---|---|---|---|---|---|---|---|",
        *rows,
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"Generated STIG traceability is stale: {OUTPUT}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
