"""Generate the executable command inventory from CommandPolicy."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from stig_audit_pro.core.command_policy import DEFAULT_COMMAND_POLICY
from stig_audit_pro.core.yaml_loader import load_check_library


OUTPUT = ROOT / "docs" / "assurance" / "COMMAND_REFERENCE.md"


def render() -> str:
    libraries = [load_check_library(path) for path in sorted((ROOT / "data" / "checks").glob("*.yaml"))]
    used_by: dict[str, list[str]] = {}
    for library in libraries:
        for check in library.checks:
            for command in check.commands:
                used_by.setdefault(command, []).append(check.vuln_id)
    lines = [
        "# Approved Command Reference",
        "",
        "> Generated by `scripts/generate_command_reference.py`. Do not edit by hand.",
        "",
        "STIG Audit Pro fails closed: a command is executable only when it exactly matches the authoritative registry after ordinary whitespace normalization. Declaring a command in YAML never grants authority.",
        "",
        "| Command | Purpose | Session only | Default collection | Bundled checks |",
        "|---|---|---:|---:|---|",
    ]
    for item in DEFAULT_COMMAND_POLICY.registry():
        checks = ", ".join(sorted(used_by.get(item.command, []))) or "—"
        lines.append(
            f"| `{item.command}` | {item.purpose} | {'Yes' if item.session_only else 'No'} | "
            f"{'Yes' if item.default_collection else 'No'} | {checks} |"
        )
    lines.extend([
        "", "## Prohibited operations", "",
        "Configuration mode, remediation, configuration writes/saves, reloads, erasure, and command chaining are not supported. Embedded line breaks, control characters, unknown commands, and unregistered pipelines are rejected before an SSH connection is attempted.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated output is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"Generated command reference is stale: {OUTPUT}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
